# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  private-nuget-feed:
    type: nuget-feed
    url: https://nuget.pkg.github.com/peddleon/index.json
    username: ${{secrets.GIT_USER}}
    password: ${{secrets.GIT_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
      timezone: "Asia/Kolkata"
    groups:
      dotnet:
        patterns:
          - "*"